export let Astro = {
  mainname: "Astro",
  data1: {
    subname: "WEB DEVLOPMENT",
    name1: "HTML",
    name2: "CSS",
    name3: "JS",
    p1: 90,
    p2: 70,
    p3: 80,
    delay: 0.3,
  },
  data2: {
    subname: "PRORAMING LANGUAG",
    name1: "PYTHON",
    name2: "C++",
    name3: "RUST",
    p1: 95,
    p2: 80,
    p3: 65,
    delay: 0.3,
  },
  data3: {
    subname: "BACKEND DEV",
    name1: "NODE.JS",
    name2: "FLASK",
    name3: "DGANGO",
    p1: 75,
    p2: 78,
    p3: 87,
    delay: 0.3,
  },
  data4: {
    subname: "EXTRA",
    name1: "LINUX",
    name2: "GITHUB",
    name3: "GIT",
    p1: 87,
    p2: 90,
    p3: 90,
    delay: 0.3,
  },
};
export let Ayushi = {
  mainname: "Ayushi",
  data1: {
    subname: "WEB DEVLOPMENT",
    name1: "HTML",
    name2: "CSS",
    name3: "JS",
    p1: 95,
    p2: 90,
    p3: 90,
    delay: 0.3,
  },
  data2: {
    subname: "PRORAMING LANGUAG",
    name1: "PYTHON",
    name2: "C++",
    name3: "java",
    p1: 95,
    p2: 80,
    p3: 90,
    delay: 0.3,
  },
  data3: {
    subname: "BACKEND DEV",
    name1: "NODE.JS",
    name2: "MongoDB",
    name3: "MySQL",
    p1: 90,
    p2: 80,
    p3: 87,
    delay: 0.3,
  },
  data4: {
    subname: "EXTRA",
    name1: "LINUX",
    name2: "GITHUB",
    name3: "GIT",
    p1: 50,
    p2: 67,
    p3: 89,
    delay: 0.3,
  },
};

export let Mahi = {
  mainname: "Mahi",
  data1: {
    subname: "WEB DEVELOPMENT",
    name1: "HTML",
    name2: "CSS",
    name3: "JS",
    p1: 85,
    p2: 75,
    p3: 80,
    delay: 0.3,
  },
  data2: {
    subname: "PROGRAMMING LANGUAGES",
    name1: "PYTHON",
    name2: "JAVA",
    name3: "C#",
    p1: 90,
    p2: 85,
    p3: 70,
    delay: 0.3,
  },
  data3: {
    subname: "BACKEND DEV",
    name1: "NODE.JS",
    name2: "EXPRESS",
    name3: "SPRING",
    p1: 80,
    p2: 75,
    p3: 85,
    delay: 0.3,
  },
  data4: {
    subname: "EXTRA",
    name1: "DOCKER",
    name2: "KUBERNETES",
    name3: "AWS",
    p1: 70,
    p2: 65,
    p3: 80,
    delay: 0.3,
  },
};

export function changepro(setFunctin, data) {
  setFunctin(data);
}
